from colorama import Fore, Back, Style
"""print(Back.WHITE+Fore.RED+"Hello I am Vihaan.What is your name?"+Style.RESET_ALL)
name=input(Back.LIGHTGREEN_EX+Fore.BLACK+"What is your name"+Fore.RED)"""
a=input(Fore.GREEN+"Write an adjective   "+Fore.CYAN)
b=input(Fore.GREEN+"Write singular of FOODS   "+Fore.CYAN)
c=input(Fore.GREEN+"Write a verb   "+Fore.CYAN)
d=input(Fore.GREEN+"Write an saying   "+Fore.CYAN)
e=input(Fore.GREEN+"Write a noun   "+Fore.CYAN)
f=input(Fore.GREEN+"Write singular of FOODS   "+Fore.CYAN)
g=input(Fore.GREEN+"Write a color name   "+Fore.CYAN)
h=input(Fore.GREEN+"Write something u ride   "+Fore.CYAN)
i=input(Fore.GREEN+"Write an animal name   "+Fore.CYAN)
j=input(Fore.GREEN+"Write a person name   "+Fore.CYAN)
print(Fore.RED+"Today I went to my favourite Taco stand called the Great  ")
print(Fore.BLUE+i+Fore.RED+".Unlike most food stands, they cook and prepare the food in a  ")
print(Fore.BLUE+h+Fore.RED+"While you ")
print(Fore.BLUE+c+Fore.RED+"The Best thing on the menu is the  "+Style.RESET_ALL)
print(Fore.BLUE+g+e+Fore.RED+".Instead of ground beef they fill the taco with Foods, cheese, and top it off with a salsa made from Foods. If that doesn't make your mouth water, then it's just like  ")
print(Fore.BLUE+j+Fore.RED+".Vihaan always says: I am good!  ")