#  libraries 
print("Types of Library:")
print("\n")
print("1.Turtle")
print("\n")
print("2.Cloroma")
print("\n")
print("3.Random")
print("\n")
print("4.Tkinter")
print("\n")
print("5.Time")
print("\n")
print("6.Date and time")
print("\n")
print("Calculator")